absl-py==1.4.0
aiofiles==22.1.0
aiohttp==3.8.4
aiosignal==1.3.1
aiosqlite==0.19.0
ale-py==0.8.1
ansi2html==1.8.0
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
astunparse==1.6.3
async-timeout==4.0.2
attrs==22.2.0
AutoROM==0.6.1
AutoROM.accept-rom-license==0.6.1
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
black==23.3.0
bleach==6.0.0
box2d-py==2.3.5
byc-pyflow==1.0.0
certifi==2023.11.17
cffi==1.15.1
cfgv==3.3.1
chardet==5.2.0
charset-normalizer==2.1.1
click==8.1.7
click-default-group==1.2.2
cloudpickle==2.2.1
cloup==0.13.1
cmake==3.26.1
colour==0.1.5
comm==0.1.3
contourpy==1.0.7
cycler==0.11.0
dask==2023.6.0
dataclasses-json==0.5.8
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.6
docutils==0.20.1
executing==1.2.0
faiss-cpu==1.7.4
Farama-Notifications==0.0.4
fastjsonschema==2.16.3
filelock==3.11.0
finta==1.3
flake8==6.0.0
Flask==2.2.3
flatbuffers==23.3.3
fonttools==4.38.0
fqdn==1.5.1
frozendict==2.4.0
frozenlist==1.3.3
fsspec==2023.6.0
gast==0.4.0
glcontext==2.3.7
google-auth==2.17.2
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.51.3
gym==0.26.2
gym-anytrading==1.3.2
gym-notices==0.0.8
gymnasium==0.28.1
h5py==3.8.0
html5lib==1.1
huggingface-hub==0.13.4
identify==2.5.24
idna==3.6
imageio==2.25.0
imageio-ffmpeg==0.4.8
importlib-metadata==5.2.0
importlib-resources==5.12.0
ipykernel==6.22.0
ipython==8.11.0
ipython-genutils==0.2.0
ipywidgets==8.0.6
isoduration==20.11.0
isosurfaces==0.1.0
itsdangerous==2.1.2
jax==0.4.8
jax-jumpy==1.0.0
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
json5==0.9.14
jsonpath-ng==1.5.3
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter-ydoc==0.2.4
jupyter_ai==0.8.0
jupyter_ai_magics==0.8.0
jupyter_client==8.1.0
jupyter_core==5.3.0
jupyter_server==2.5.0
jupyter_server_fileid==0.9.0
jupyter_server_terminals==0.4.4
jupyter_server_ydoc==0.8.0
jupyterlab==3.6.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
jupyterlab_server==2.23.0
keras==2.12.0
keras-rl2==1.0.5
Kivy==2.2.0
Kivy-examples==2.2.0
Kivy-Garden==0.1.5
kiwisolver==1.4.4
langchain==0.0.159
libclang==16.0.0
lit==16.0.0
locket==1.0.0
lxml==5.1.0
manim==0.17.0
manimlib==0.2.0
ManimPango==0.4.2
mapbox-earcut==1.0.1
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.2
marshmallow==3.19.0
marshmallow-enum==1.5.1
matplotlib==3.6.3
matplotlib-inline==0.1.6
mccabe==0.7.0
mdurl==0.1.2
mistune==2.0.5
ml-dtypes==0.0.4
moderngl==5.7.2
moderngl-window==2.4.2
mpmath==1.3.0
msgpack==1.0.5
multidict==6.0.4
multipledispatch==0.6.0
multitasking==0.0.11
mypy-extensions==1.0.0
nbclassic==0.5.5
nbclient==0.7.3
nbconvert==7.3.0
nbformat==5.8.0
nd2==0.5.3
nest-asyncio==1.5.6
networkx==2.8.8
nodeenv==1.8.0
notebook==6.5.4
notebook_shim==0.2.2
numexpr==2.8.4
numpy==1.23.5
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
openai==0.27.8
openapi-schema-pydantic==1.2.4
opencv-python==4.6.0.66
opt-einsum==3.3.0
packaging==23.0
pandas==1.5.3
pandocfilters==1.5.0
parso==0.8.3
partd==1.4.0
pathspec==0.11.1
peewee==3.17.1
pickleshare==0.7.5
Pillow==10.1.0
pkginfo==1.9.6
platformdirs==3.5.1
ply==3.11
polars==0.18.2
pre-commit==3.3.2
progressbar==2.5
prometheus-client==0.16.0
prompt-toolkit==3.0.38
protobuf==4.22.1
psutil==5.9.4
pure-eval==0.2.2
pycairo==1.23.0
pycodestyle==2.10.0
pycparser==2.21
pydantic==1.10.9
pydub==0.25.1
pyflakes==3.0.1
pygame==2.1.0
pyglet==1.3.2
Pygments==2.17.2
PyMuPDF==1.24.9
PyMuPDFb==1.24.9
pypdf==4.3.1
PyPDF2==2.11.0
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.1
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2
pyrr==0.10.3
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2022.7.1
PyWavelets==1.4.1
pyzmq==25.0.2
QScintilla==2.13.4
qtconsole==5.4.2
QtPy==2.3.1
ray==2.4.0
readme-renderer==37.3
regex==2023.3.23
reportlab==3.6.12
requests==2.31.0
requests-oauthlib==1.3.1
requests-toolbelt==1.0.0
resource-backed-dask-array==0.1.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.0
scikit-image==0.19.3
scipy==1.9.3
screeninfo==0.8.1
seaborn==0.12.2
Send2Trash==1.8.0
sentencepiece==0.1.97
six==1.16.0
skia-pathops==0.7.4
soupsieve==2.4
srt==3.5.2
stable-baselines==2.10.2
stable-baselines3==1.8.0
stack-data==0.6.2
svgelements==1.8.4
swig==4.1.1
sympy==1.11.1
tenacity==8.2.2
tensorboard==2.12.1
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
tensorflow==2.12.0
tensorflow-estimator==2.12.0
tensorflow-io-gcs-filesystem==0.32.0
termcolor==2.2.0
terminado==0.17.1
tifffile==2023.1.23.1
tiktoken==0.4.0
tinycss2==1.2.1
tokenizers==0.13.3
toolz==0.12.0
torch==2.0.0
tornado==6.2
tqdm==4.64.1
traitlets==5.9.0
transformers==4.27.4
triton==2.0.0
twine==4.0.2
typing-inspect==0.9.0
typing_extensions==4.5.0
uri-template==1.2.0
urllib3==2.1.0
virtualenv==20.21.0
watchdog==2.1.9
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.5.1
Werkzeug==2.2.3
widgetsnbextension==4.0.7
wrapt==1.14.1
y-py==0.5.9
yarl==1.9.2
yfinance==0.2.37
ypy-websocket==0.8.2
